Repository coral-erm/coral, pull requests merged in 2018-10, with the labels that each got.

#469 Fix access method deletion in admin
  resources/admin/classes/domain/AccessMethod.php
Labels: bug

#453 Restore workflow archiving fix
  resources/admin/classes/domain/ResourceAcquisition.php
Labels: bug

#499 Fix resources menu display for turkish translation
  resources/admin/classes/domain/User.php
Labels: bug, help wanted

#447 Issue 446: Fix end date alert
  resources/admin/classes/domain/AlertDaysInAdvance.php
Labels: bug

#496 Fix hard-coded dates in SushiService
  usage/admin/classes/domain/SushiService.php
Labels: bug

#495 OAuth authentication: bugfix and enhancements
  organizations/admin/classes/api_client/KohaClient.php
  organizations/admin/classes/api_client/OAuth.php
  organizations/admin/interfaces/ILSClient.php
  organizations/ajax_processing.php
  organizations/js/forms/organizationSubmitForm.js
  resources/api_client/composer.json
Labels: bug, enhancement

#466 Fix access edition when using icon link
  resources/ajax_htmldata/getAccessDetails.php
Labels: bug, good first issue

#487 Licensing: Restore Resource Linking in the Helpful Links sidebar
  licensing/admin/classes/domain/License.php
Labels: bug

#452 Issue 450: Fix edition/deletion of local account
  resources/ajax_htmldata/getAccountDetails.php
Labels: bug, good first issue

#505 Fix licensing calendar bad query failure
  licensing/calendar.php
Labels: bug

#436 Add an option to save import configuration on the fly
  resources/css/style.css
  resources/import.php
Labels: bug, enhancement

#416 Issue 412: Change email address to its plural form
  resources/ajax_forms/getAdminUserGroupForm.php
Labels: bug, good first issue

#444 Make resource and usage sidemenus translatable
  resources/directory.php
  usage/directory.php
  usage/images/acquisitions.gif
  usage/images/acquisitions_bw.gif
  usage/images/arrow_sides.gif
  usage/images/arrow_sides_bw.gif
  usage/images/key.gif
  usage/images/key_bw.gif
  usage/images/seahorseicon.png
  usage/images/seahorseicon_bw.png
  usage/images/xls.gif
  usage/images/xls_bw.gif
Labels: bug, refactor

#501 Improvements to the order dropdown list
  resources/admin/classes/domain/Resource.php
  resources/admin/classes/domain/ResourceAcquisition.php
  resources/css/style.css
  resources/resource.php
Labels: enhancement

#507 Issue 493: Fix acquisition Type in import
  resources/import.php
Labels: bug
