Repository coral-erm/coral, pull requests merged in 2018-11, with the labels that each got.

#467 Add PIG (Public Interface Generator) addon into main Coral repository
  resources/README.md
  resources/admin/classes/domain/PigResource.php
  resources/admin/configuration_sample.ini
  resources/images/pig_XML_icon.png
  resources/images/pig_balloon_icon.png
  resources/js/pig.js
  resources/pig.php
  resources/pig_ajax_htmldata.php
  resources/pig_htmldata.php
  resources/pig_search.php
  resources/pig_xmldata.php
  resources/readme_pig.txt
  resources/templates/pig_header.php
Labels: enhancement

#465 Issue #460, adds correct database name to report db queries
  reports/admin/classes/domain/ParameterFactory.php
  reports/admin/classes/report/Report.php
Labels: bug

#511 Fix import page translation
  resources/import.php
Labels: bug

#509 Issue 478: Allow subscription start and end date to be null
  resources/admin/classes/domain/ResourceAcquisition.php
  resources/ajax_processing/submitAcquisitions.php
  resources/install/protected/3.0.1/001-478.sql
  resources/resource.php
Labels: bug

#503 Issue 470 export resources bug
  auth/install/auth.php
  install/index.php
  install/providers/db_tools.php
  licensing/install/licensing.php
  management/install/management.php
  organizations/install/organizations.php
  reports/install/reports.php
  resources/install/protected/3.0.1/001-470.sql
  resources/install/resources.php
  usage/install/usage.php
Labels: bug, release blocking
