Repository coral-erm/coral, pull requests merged in 2018-03, with the labels that each got.

#356 Issue #355: fix PHP Notices on Organizations index page.
  organizations/index.php
Labels: bug

#349 Remove orders on resource deletion
  resources/admin/classes/domain/Resource.php
  resources/admin/classes/domain/ResourceAcquisition.php
  resources/ajax_htmldata/getAcquisitionsDetails.php
  resources/ajax_htmldata/getContactDetails.php
  resources/ajax_processing/submitNewResource.php
  resources/js/resource.js
  resources/resources/cataloging.php
Labels: bug

#373 Make Ebsco KB integration translatable
  resources/ajax_htmldata/getEbscoKbTitleDetails.php
  resources/ajax_htmldata/getSearchEbscoKb.php
  resources/templates/ebscoKbPackageList.php
  resources/templates/ebscoKbTitleList.php
Labels: bug

#366 Fix dashboards for multiple ordering
  resources/admin/classes/common/Dashboard.php
Labels: bug

#308 Issue #55: adopt the Drupal `.editorconfig` file.
  .editorconfig
Labels: plumbing

#391 Allow to close a modal popup with the escape key
  resources/js/plugins/thickbox.js
Labels: bug

#395 Allow to close a modal popup with the escape key (other modules)
  licensing/js/plugins/thickbox.js
  management/js/plugins/thickbox.js
  organizations/js/plugins/thickbox.js
  reports/js/plugins/thickbox.js
  usage/js/plugins/thickbox.js
Labels: bug

#320 SirsiDynix Issues: Not all dates are formatted based on setting in directory.php
  management/ajax_forms.php
  resources/ajax_forms/getCostForm.php
  resources/ajax_forms/getOrderForm.php
  resources/ajax_htmldata/getSavedQueue.php
  resources/ajax_htmldata/getSubmittedQueue.php
Labels: bug, important

#315 SirsiDynix Issues: Emails not sent to organizational contacts
  resources/ajax_processing/insertIssue.php
Labels: bug, important
