Repository coral-erm/coral, pull requests merged in 2018-02, with the labels that each got.

#343 Issue 145 [Follow-up]: Use singleton for database connection
  auth/admin/classes/common/DBService.php
  auth/admin/classes/common/DatabaseObject.php
  licensing/admin/classes/common/DBService.php
  licensing/admin/classes/common/DatabaseObject.php
  licensing/admin/classes/common/Utility.php
  management/admin/classes/common/DBService.php
  management/admin/classes/common/DatabaseObject.php
  management/admin/classes/common/Utility.php
  organizations/admin/classes/common/DBService.php
  organizations/admin/classes/common/DatabaseObject.php
  reports/admin/classes/common/DBService.php
  reports/admin/classes/domain/ParameterFactory.php
  reports/admin/classes/report/Report.php
  reports/index.php
  usage/admin/classes/common/DBService.php
  usage/admin/classes/common/DatabaseObject.php
  usage/admin/classes/domain/Platform.php
Labels: plumbing

#354 Issue #302: Sequenced sql files
  auth/install/auth.php
  auth/install/protected/.htaccess
  auth/install/protected/2.0.0/001-000.sql
  auth/install/protected/coral_auth_data_model.pdf
  auth/install/protected/coral_reporting_data_model.pdf
  auth/install/protected/install.sql
  auth/install/protected/test_create.sql
  install/index.php
  install/providers/db_tools.php
  licensing/install/licensing.php
  licensing/install/protected/2.0.0/001-000.sql
  management/install/management.php
  management/install/protected/2.0.0/001-000.sql
  organizations/install/organizations.php
  organizations/install/protected/.htaccess
  organizations/install/protected/coral_organizations_data_model.pdf
  organizations/install/protected/install.sql
  organizations/install/protected/test_create.sql
  organizations/install/protected/update_latin1-to-utf8.sql
  organizations/install/protected/upgrade_1.3.sql
  organizations/install/protected/upgrade_1_1.sql
  organizations/install/protected/upgrade_issues_enhancements.sql
  reports/install/protected/.htaccess
  reports/install/protected/install.sql
  reports/install/protected/test_create.sql
  reports/install/reports.php
  resources/install/protected/2.0.0/001-000.sql
  resources/install/protected/2.1.0/002-350.sql
  resources/install/protected/2.1.0/003-334.sql
  resources/install/protected/install.sql
  resources/install/resources.php
  usage/install/usage.php
Labels: plumbing

#334 SirsiDynix: EBSCO kb integration
  organizations/admin/classes/domain/Organization.php
  organizations/install/protected/2.1.0/003-334.sql
  organizations/install/protected/install.sql
  resources/admin.php
  resources/admin/classes/domain/DetailedSubject.php
  resources/admin/classes/domain/EbscoKbCustomerResource.php
  resources/admin/classes/domain/EbscoKbHoldings.php
  resources/admin/classes/domain/EbscoKbPackage.php
  resources/admin/classes/domain/EbscoKbResult.php
  resources/admin/classes/domain/EbscoKbService.php
  resources/admin/classes/domain/EbscoKbTitle.php
  resources/admin/classes/domain/EbscoKbVendor.php
  resources/admin/classes/domain/GeneralSubject.php
  resources/admin/classes/domain/Organization.php
  resources/admin/classes/domain/Resource.php
  resources/admin/classes/domain/ResourceType.php
  resources/ajax_forms/getEbscoKbPackageImportForm.php
  resources/ajax_forms/getEbscoKbTitleImportForm.php
  resources/ajax_htmldata/getAdminEbscoKbConfigDisplay.php
  resources/ajax_htmldata/getEbscoKbTitleDetails.php
  resources/ajax_htmldata/getRightPanel.php
  resources/ajax_htmldata/getSearchEbscoKb.php
  resources/ajax_processing/importFromEbscoKb.php
  resources/ajax_processing/updateEbscoKbConfig.php
  resources/css/ebscoKbCss.php
  resources/css/style.css
  resources/ebsco_kb.php
  resources/images/menu/icon-ebsco.png
  resources/install/protected/install.sql
  resources/js/admin.js
  resources/js/ebsco_kb.js
  resources/js/forms/importEbscoKbForm.js
  resources/js/resource.js
  resources/resource.php
  resources/templates/ebscoKbPackageList.php
  resources/templates/ebscoKbTitleList.php
  resources/templates/ebscoKbVendorList.php
  resources/templates/header.php
Labels: enhancement

#362 fixes #361
  resources/api_client/index.php
Labels: bug
