Repository coral-erm/coral, pull requests merged in 2018-04, with the labels that each got.

#236 Add item to GROUP BY for new MySQL 5.7 default compatibility.
  organizations/admin/classes/domain/Organization.php
Labels: bug

#371 Remove CSS rules for capitalization
  auth/css/style.css
  licensing/css/style.css
  management/css/style.css
  organizations/css/style.css
  reports/css/style.css
  resources/css/style.css
  usage/css/style.css
Labels: bug

#404 Issues 103, 403: Fix selected language in dropdown when language cookie is not set.
  LangCodes.php
  auth/admin.php
  auth/index.php
  index.php
  licensing/templates/header.php
  management/templates/header.php
  organizations/templates/header.php
  reports/index.php
  resources/templates/header.php
  usage/templates/header.php
Labels: bug

#396 Fix CSV export
  resources/admin/classes/domain/Resource.php
  resources/export.php
Labels: bug

#328 SirsiDynix Issues: Manual Stats Imports failing
  usage/admin/classes/common/Utility.php
  usage/uploadComplete.php
Labels: bug, important

#401 Issue 258: Fixes Importing issues
  usage/admin/classes/domain/MonthlyUsageSummary.php
  usage/admin/classes/domain/SushiService.php
  usage/admin/classes/domain/YearlyUsageSummary.php
  usage/metrics.ini
Labels: bug, release blocking

#392 #332 installer bug fix
  install/providers/have_database_access.php
  install/providers/have_default_db_user.php
  organizations/install/protected/install.sql
  resources/install/protected/install.sql
Labels: bug, important, release blocking

#402 Issue 394 installer 3.0.0
  auth/install/auth.php
  install/index.php
  licensing/install/licensing.php
  management/install/management.php
  organizations/install/organizations.php
  organizations/install/protected/3.0.0/003-334.sql
  reports/install/reports.php
  resources/install/protected/3.0.0/001-318.sql
  resources/install/protected/3.0.0/002-350.sql
  resources/install/protected/3.0.0/003-334.sql
  resources/install/resources.php
  usage/install/usage.php
Labels: refactor, release blocking

#390 Fix multiple issues with resource submission
  resources/admin/classes/domain/Resource.php
  resources/ajax_forms/getNewResourceForm.php
  resources/ajax_processing/submitNewResource.php
Labels: bug, important

#337 Restore ability for org Issue class to represent resource module Issue table
  organizations/admin/classes/common/DatabaseObject.php
Labels: bug

#378 Allow to use OAuth for the ILS connector
  organizations/admin/classes/api_client/INSTALL
  organizations/admin/classes/api_client/KohaClient.php
  organizations/admin/classes/api_client/OAuth.php
  organizations/admin/configuration_sample.ini
Labels: enhancement

#367 API: Fix licenses route
  licensing/admin/classes/domain/License.php
  resources/admin/classes/domain/Resource.php
  resources/api/index.php
Labels: bug, enhancement

#409 Fix for #408 edge db_user check bug
  install/providers/have_default_db_user.php
Labels: bug
