Repository coral-erm/coral, pull requests merged in 2020-02, with the labels that each got.

#583 SirsiDynix: EBSCO Kb Interface Updates
  resources/admin/classes/domain/EbscoKbService.php
  resources/admin/classes/domain/EbscoKbTitle.php
  resources/ajax_forms/getEbscoKbPackageImportForm.php
  resources/ajax_forms/getEbscoKbRemoveConfirmation.php
  resources/ajax_forms/getEbscoKbTitleImportForm.php
  resources/ajax_htmldata/getEbscoKbTitleDetails.php
  resources/ajax_htmldata/getEbscoKbTitleStatus.php
  resources/ajax_processing/importFromEbscoKb.php
  resources/ajax_processing/setEbscoKbSelection.php
  resources/css/ebscoKbCss.php
  resources/css/style.css
  resources/ebsco_kb.php
  resources/js/ebsco_kb.js
  resources/js/forms/importEbscoKbForm.js
  resources/templates/ebscoKbPackageDropdown.php
  resources/templates/ebscoKbPackageList.php
  resources/templates/ebscoKbTitleList.php
Labels: bug, enhancement, help wanted

#488 Adds Terms tool code into Coral
  .gitignore
  common/safe_file_rewrite.php
  common/write_php_ini.php
  licensing/admin.php
  licensing/admin/classes/domain/EBSCOService.php
  licensing/admin/classes/domain/Expression.php
  licensing/admin/classes/domain/ExpressionType.php
  licensing/admin/classes/domain/SFXService.php
  licensing/admin/classes/domain/SerialsSolutionsService.php
  licensing/admin/classes/domain/TermsService.php
  licensing/admin/configuration_sample.ini
  licensing/ajax_forms.php
  licensing/ajax_htmldata.php
  licensing/ajax_processing.php
  licensing/css/base-terms.css
  licensing/css/terms.css
  licensing/images/arrowright.gif
  licensing/images/icon_check.gif
  licensing/images/icon_x.gif
  licensing/install/licensing.php
  licensing/js/admin.js
  licensing/terms.php
  resources/ajax_processing/updateEbscoKbConfig.php
Labels: enhancement, good first issue, help wanted

#631 Add common classes to the reports module
  reports/admin/classes/common/Base_Object.php
  reports/admin/classes/common/Configuration.php
  reports/admin/classes/common/DynamicObject.php
  reports/admin/classes/common/NamedArguments.php
  reports/admin/classes/common/Utility.php
Labels: bug
