Repository coral-erm/coral, pull requests merged in 2020-01, with the labels that each got.

#620 Upgrade file uploads
  auth/admin.php
  auth/index.php
  common/common_directory.php
  js/plugins/ajaxupload.3.5.js
  js/plugins/jquery-1.11.3.js
  js/plugins/jquery-1.4.4.js
  js/plugins/jquery.datePicker-patched-for-i18n.js
  licensing/ajax_processing.php
  licensing/images/view.gif
  licensing/js/forms/attachmentForm.js
  licensing/js/forms/documentForm.js
  licensing/js/license.js
  licensing/js/plugins/ajaxupload.3.5.js
  licensing/license.php
  licensing/templates/header.php
  management/ajax_processing.php
  management/js/forms/attachmentForm.js
  management/js/forms/documentForm.js
  management/js/forms/licenseForm.js
  management/js/license.js
  management/templates/header.php
  organizations/summary.php
  organizations/templates/header.php
  reports/popup.php
  reports/templates/header.php
  resources/ajax_processing/uploadAttachment.php
  resources/dashboard.php
  resources/dashboard_yearly_costs.php
  resources/js/forms/attachmentForm.js
  resources/resource.php
  resources/templates/header.php
  resources/templates/pig_header.php
  usage/templates/header.php
Labels: bug, refactor

#558 Issue 482: Fix Resource Get Statistics button
  resources/ajax_htmldata/getRightPanel.php
Labels: bug

#624 Issue 623: Search resources with no relationship
  resources/admin/classes/domain/Resource.php
  resources/index.php
Labels: enhancement

#547 Fix licensing calendar
  licensing/calendar.php
Labels: bug, help wanted

#621 Issue 601: Keep search parameters in resource module
  resources/index.php
  resources/resource.php
Labels: bug
